import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { ethers } from "ethers";
import { useEffect, useState } from "react";
 
const Home: NextPage = () => {
 const [provider, setProvider] = useState<any>(null);
 const [signer, setSigner] = useState<any>(null);
 const [balance, setBalance] = useState<string>("0");
 const [account, setAccount] = useState<string | null>(null);
 
 useEffect(() => {
 if (window.ethereum) {
 console.log("MetaMask is installed!");
 const provider = new ethers.providers.Web3Provider(window.ethereum);
 setProvider(provider);
 const signer = provider.getSigner();
 setSigner(signer);
 } else {
 console.log("Please install MetaMask!");
 }
 }, []);
 
 useEffect(() => {
 if (signer) {
 signer.getAddress().then((address: string) => setAccount(address));
 }
 }, [signer]);
 
 useEffect(() => {
 if (provider && account) {
 provider.getBalance(account).then((balance) => {
 setBalance(ethers.utils.formatEther(balance));
 });
 }
 }, [provider, account]);
 
  return (
    <div className={styles.container}>
      <Head>
        <title>Eleve Here</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
 
      <main className={styles.main}>
        <ConnectButton />
        <p>Address: {account}</p>
        <p>Amount: {balance}</p>
        <form>
          <label>prenom</label>
          <input type="text"/>
          <label>prenom</label>
          <input type="text"/>
          <label>age</label>
          <input type="number" />
          <label>cursus</label>
          <input type="text"/>
        </form>
      </main>
    </div>
  );
};

export default Home;